apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-me
  labels:
    app: http-server
spec:
  selector:
    matchLabels:
      app: http-server
  replicas: 2
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server-metrics
          image: xxx
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

